Repository emackinnon1/oversite-fe, pull requests merged in 2020-07, with the labels that each got.

#1 Feature/search results
  pull-request-template.md
  src/components/AllReps/AllReps.css
  src/components/AllReps/AllReps.js
  src/components/AllReps/AllReps.test.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/ResultCard/ResultCard.css
  src/components/ResultCard/ResultCard.js
  src/components/ResultPage/ResultPage.css
  src/components/ResultPage/ResultPage.js
  src/components/ResultPage/ResultPage.test.js
  src/components/ResultsPage/ResultPage.test.js
Labels: enhancement

#2 Homepage
  package-lock.json
  package.json
  public/images/search.svg
  src/components/App/App.js
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/index.css
  src/index.js
Labels: enhancement

#3 Added styling to NavBar and Homepage
  src/components/App/App.css
  src/components/App/App.js
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
Labels: enhancement

#4 Rep details page
  public/images/capital_hill.png
  src/components/App/App.js
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.css
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
  src/components/SingleRep/SingleRep.test.js
Labels: enhancement

#5 Set up dummy tests
  src/components/AllReps/AllReps.test.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/HomePage/HomePage.test.js
  src/components/Navbar/Navbar.test.js
  src/components/ResultCard/ResultCard.test.js
  src/components/ResultPage/ResultPage.test.js
  src/components/SingleRep/SingleRep.test.js
Labels: Testing

#6 Add .circleci/config.yml
  .circleci/config.yml
Labels: Testing

#7 Add styling to results page and all reps page
  src/components/AllReps/AllReps.css
  src/components/AllReps/AllReps.js
  src/components/App/App.css
  src/components/ResultCard/ResultCard.css
  src/components/ResultPage/ResultPage.css
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
Labels: enhancement

#8 Homepage fix
  public/images/usa_seal.svg
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
Labels: enhancement

#9 Feature/context hook
  src/components/App/userContext.js
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.js
  src/index.js
Labels: enhancement

#11 Feature/user
  public/images/search.svg
  public/images/user_icon.svg
  pull-request-template.md
  src/apiCalls.js
  src/components/App/App.js
  src/components/App/userContext.js
  src/components/Collapsible/Collapsible.css
  src/components/Collapsible/Collapsible.js
  src/components/HomePage/HomePage.test.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
Labels: enhancement

#13 Env setup
  .env
  package.json
  src/apiCalls.js
  src/apiConfig.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.js
  src/components/StatePicker/StatePicker.js
  src/index.css
  src/index.js
Labels: enhancement

#12 Update user icon info
  .gitignore
Labels: enhancement

#10 Test/return card unit
  src/components/ResultCard/ResultCard.js
  src/components/ResultCard/ResultCard.test.js
Labels: Testing

#15 Feature/single rep view buildout
  src/apiCalls.js
  src/components/App/App.js
  src/components/ResultCard/ResultCard.js
  src/components/ResultPage/ResultPage.css
  src/components/ResultPage/ResultPage.js
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
Labels: enhancement

#16 Feature/tweet rep functionality
  public/images/contact_form_icon.svg
  public/images/facebook_icon.svg
  public/images/logo_icon.svg
  public/images/youtube_icon.svg
  src/apiCalls.js
  src/components/App/App.js
  src/components/Navbar/Navbar.css
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
Labels: enhancement

#17 404 page v2
  public/images/404_page.png
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Error/Error.test.js
  src/components/HomePage/HomePage.test.js
Labels: enhancement

#18 Feature/tweet rep functionality
  src/apiCalls.js
  src/components/ResultPage/ResultPage.js
Labels: enhancement

#20 Home page style fix
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
  src/components/StatePicker/StatePicker.css
  src/components/StatePicker/StatePicker.js
Labels: enhancement

#21 Feature/my reps buildout
  src/apiCalls.js
  src/components/AllReps/AllReps.css
  src/components/AllReps/AllReps.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Navbar/Navbar.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Profile/Profile.test.js
  src/components/ResultCard/ResultCard.js
  src/components/ResultPage/ResultPage.css
  src/components/ResultPage/ResultPage.js
Labels: enhancement

#22 Single rep style fix
  package-lock.json
  package.json
  src/components/ResultCard/ResultCard.css
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
  src/index.css
Labels: enhancement

#23 Test/integration
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/AppMockData.js
  src/components/Error/Error.test.js
  src/components/HomePage/HomePage.js
  src/components/Navbar/Navbar.test.js
  src/components/Profile/Profile.js
  src/components/Profile/Profile.test.js
  src/components/ResultCard/ResultCard.js
  src/components/SingleRep/SingleRep.js
  src/components/StatePicker/StatePicker.js
Labels: Testing

#24 Results page restyle
  public/images/image-not-found.png
  src/components/ResultCard/ResultCard.css
  src/components/ResultCard/ResultCard.js
  src/components/ResultPage/ResultPage.css
  src/components/ResultPage/ResultPage.js
Labels: enhancement

#26 Fixes/final style
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/ResultCard/ResultCard.css
  src/components/SingleRep/SingleRep.css
  src/components/SingleRep/SingleRep.js
  src/index.css
Labels: enhancement

#28 Fix styling for the profile page
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/ResultPage/ResultPage.css
Labels: enhancement

#30 Update README.md
  README.md
  public/index.html
  public/logoo.png
Labels: enhancement

#32 Readme addon
  README.md
Labels: ReadME

#34 Update README.md
  README.md
Labels: ReadME
